export const structuredData = {
  '@context': 'https://schema.org',
  '@graph': [
    {
      '@type': 'CateringService',
      '@id': 'https://sonokembang.id/#organization',
      name: 'Sonokembang Catering',
      alternateName: 'Sonokembang',
      url: 'https://sonokembang.id',
      logo: 'https://sonokembang.id/assets/logo-sonokembang-large.png',
      image: 'https://sonokembang.id/assets/hero-wedding-spread.jpg',
      description:
        'Sonokembang Catering melayani pernikahan, syukuran, khitanan, dan acara keluarga di 6 kota Indonesia. Berdiri sejak 1987 di Surabaya.',
      foundingDate: '1987',
      founder: {
        '@type': 'Person',
        name: 'Ibu Sri Harjoeni',
      },
      areaServed: [
        { '@type': 'City', name: 'Surabaya' },
        { '@type': 'City', name: 'Malang' },
        { '@type': 'City', name: 'Jakarta' },
        { '@type': 'City', name: 'Semarang' },
        { '@type': 'City', name: 'Banjarmasin' },
      ],
      serviceType: [
        'Catering Pernikahan',
        'Catering Syukuran',
        'Catering Khitanan',
        'Prasmanan',
        'Nasi Box',
        'Hantaran',
        'Tumpeng',
      ],
      hasOfferCatalog: {
        '@type': 'OfferCatalog',
        name: 'Layanan Catering Sonokembang',
        itemListElement: [
          {
            '@type': 'Offer',
            itemOffered: {
              '@type': 'Service',
              name: 'Catering Pernikahan',
              description: 'Prasmanan dan nasi box untuk resepsi pernikahan, minimum 50 pax.',
            },
          },
          {
            '@type': 'Offer',
            itemOffered: {
              '@type': 'Service',
              name: 'Catering Syukuran & Khitanan',
              description: 'Paket tumpeng, nasi box, dan prasmanan untuk acara keluarga, minimum 20 pax.',
            },
          },
          {
            '@type': 'Offer',
            itemOffered: {
              '@type': 'Service',
              name: 'Hantaran Premium',
              description: 'Besek, tenong, dan Zamrud Premium Box untuk Lebaran dan acara spesial.',
            },
          },
        ],
      },
      sameAs: [
        'https://instagram.com/sonokembangsby',
        'https://instagram.com/sonokembangcateringmlg',
        'https://instagram.com/sonokembangjakarta',
        'https://instagram.com/sonokembangprestige',
        'https://instagram.com/sonokembangbanjarmasin',
        'https://tiktok.com/@sonokembangsby',
      ],
    },
    {
      '@type': 'LocalBusiness',
      '@id': 'https://sonokembang.id/#surabaya',
      name: 'Sonokembang Catering Surabaya',
      parentOrganization: { '@id': 'https://sonokembang.id/#organization' },
      address: {
        '@type': 'PostalAddress',
        streetAddress: 'Jl. Adityawarman 60',
        addressLocality: 'Surabaya',
        addressRegion: 'Jawa Timur',
        addressCountry: 'ID',
      },
      telephone: '+628113000000',
      url: 'https://sonokembang.id',
      image: 'https://sonokembang.id/assets/hero-wedding-spread.jpg',
    },
    {
      '@type': 'LocalBusiness',
      '@id': 'https://sonokembang.id/#malang',
      name: 'Sonokembang Catering Malang',
      parentOrganization: { '@id': 'https://sonokembang.id/#organization' },
      address: {
        '@type': 'PostalAddress',
        streetAddress: 'Jl. Bandung 4',
        addressLocality: 'Malang',
        addressRegion: 'Jawa Timur',
        addressCountry: 'ID',
      },
      telephone: '+628113111111',
    },
    {
      '@type': 'LocalBusiness',
      '@id': 'https://sonokembang.id/#jakarta',
      name: 'Sonokembang Catering Jakarta',
      parentOrganization: { '@id': 'https://sonokembang.id/#organization' },
      address: {
        '@type': 'PostalAddress',
        streetAddress: 'Kuningan',
        addressLocality: 'Jakarta Selatan',
        addressRegion: 'DKI Jakarta',
        addressCountry: 'ID',
      },
      telephone: '+628113222222',
    },
    {
      '@type': 'WebSite',
      '@id': 'https://sonokembang.id/#website',
      url: 'https://sonokembang.id',
      name: 'Sonokembang Catering',
      publisher: { '@id': 'https://sonokembang.id/#organization' },
      inLanguage: 'id',
    },
  ],
}
