export const CITIES = [
  {
    id: "surabaya",
    name: "Surabaya",
    badge: "Flagship · Sejak 1987",
    tagline: "Rumah dari Sonokembang Catering",
    note: "Tempat di mana semuanya dimulai — kanteen Ibu Sri Harjoeni di Jalan Sono, kini melayani pernikahan dan syukuran di seluruh Jawa Timur.",
    handle: "@sonokembangsby",
    accent: "var(--sk-emerald)",
    accentSoft: "var(--sk-emerald-700)",
    cover: "/assets/hero-wedding-spread.jpg",
    feed: ["/assets/food-01.jpg","/assets/menu-01.png","/assets/food-04.jpg","/assets/menu-04.jpg","/assets/food-02.jpg","/assets/menu-02.png"],
    links: {
      gmaps: "https://maps.google.com/?q=Sonokembang+Catering+Surabaya",
      ig:    "https://instagram.com/sonokembangsby",
      wa:    "https://wa.me/628113000000",
      tiktok:"https://tiktok.com/@sonokembangsby",
    },
    address: "Jl. Adityawarman 60, Surabaya",
  },
  {
    id: "malang",
    name: "Malang",
    badge: "#RayakanMomenmu",
    tagline: "Catering pernikahan & syukuran kota dingin",
    note: "Acara wedding, khitanan, arisan keluarga — diracik untuk udara sejuk Malang dengan menu khas Jawa Timuran.",
    handle: "@sonokembangcateringmlg",
    accent: "var(--sk-batik-brown)",
    accentSoft: "var(--sk-batik-tan)",
    cover: "/assets/food-03.jpg",
    feed: ["/assets/menu-03.png","/assets/food-05.jpg","/assets/menu-05.png","/assets/food-06.jpg","/assets/menu-06.png","/assets/food-01.jpg"],
    links: {
      gmaps: "https://maps.google.com/?q=Sonokembang+Catering+Malang",
      ig:    "https://instagram.com/sonokembangcateringmlg",
      wa:    "https://wa.me/628113111111",
      tiktok:"https://tiktok.com/@sonokembangcateringmlg",
    },
    address: "Jl. Bandung 4, Malang",
  },
  {
    id: "jakarta",
    name: "Jakarta",
    badge: "Ibu Kota",
    tagline: "Heritage rasa Jawa di tengah metropolitan",
    note: "Prasmanan kantor, hantaran besek, dan tumpeng syukuran untuk klien korporat dan keluarga di Jabodetabek.",
    handle: "@sonokembangjakarta",
    accent: "var(--sk-red-deep)",
    accentSoft: "var(--sk-red)",
    cover: "/assets/menu-07.png",
    feed: ["/assets/menu-07.png","/assets/menu-08.png","/assets/food-02.jpg","/assets/food-04.jpg","/assets/menu-01.png","/assets/menu-04.jpg"],
    links: {
      gmaps: "https://maps.google.com/?q=Sonokembang+Catering+Jakarta",
      ig:    "https://instagram.com/sonokembangjakarta",
      wa:    "https://wa.me/628113222222",
      tiktok:"https://tiktok.com/@sonokembangjakarta",
    },
    address: "Kuningan, Jakarta Selatan",
  },
  {
    id: "semarang",
    name: "Semarang",
    badge: "Prestige",
    tagline: "Nasi box, hantaran & tumpeng premium",
    note: "Cabang Sonokembang Prestige — katalog e-commerce untuk Han.ta.ran, Zamrud Premium Box, dan Premium Nusantara.",
    handle: "@sonokembangprestige",
    accent: "var(--sk-gold-deep)",
    accentSoft: "var(--sk-gold)",
    cover: "/assets/menu-02.png",
    feed: ["/assets/menu-08.png","/assets/menu-02.png","/assets/menu-06.png","/assets/menu-05.png","/assets/food-03.jpg","/assets/menu-03.png"],
    links: {
      gmaps: "https://maps.google.com/?q=Sonokembang+Prestige+Semarang",
      ig:    "https://instagram.com/sonokembangprestige",
      wa:    "https://wa.me/628113333333",
      tiktok:"https://tiktok.com/@sonokembangprestige",
    },
    address: "Jl. Pemuda, Semarang",
  },
  {
    id: "banjarmasin",
    name: "Banjarmasin",
    badge: "Kalimantan Selatan",
    tagline: "Cita rasa Jawa, tangan Banjar",
    note: "Cabang lintas pulau yang menyajikan menu Sonokembang dengan sentuhan rempah Kalimantan untuk acara adat dan keluarga.",
    handle: "@sonokembangbanjarmasin",
    accent: "var(--sk-emerald-500)",
    accentSoft: "var(--sk-emerald-300)",
    cover: "/assets/food-06.jpg",
    feed: ["/assets/food-06.jpg","/assets/menu-04.jpg","/assets/food-05.jpg","/assets/menu-05.png","/assets/food-01.jpg","/assets/menu-01.png"],
    links: {
      gmaps: "https://maps.google.com/?q=Sonokembang+Catering+Banjarmasin",
      ig:    "https://instagram.com/sonokembangbanjarmasin",
      wa:    "https://wa.me/628113444444",
      tiktok:"https://tiktok.com/@sonokembangbanjarmasin",
    },
    address: "Jl. A. Yani Km. 5, Banjarmasin",
  },
];
